In [1]:
import pandas as pd
import numpy as np

# **Brakujące wartości**

**Brakujące wartości** to rekordy, które są nieobecne w zestawie danych.

**Przyczyny występowania**:
* Błąd człowieka podczas wprowadzania danych​

* Ochrona prywatności (dane wrażliwe)
* Brak odpowiedzi w ankietach

Problemy techniczne przy zbieraniu danych

Jest to jeden z **najczęściej występujących problemów** w analizie danych i kluczowy etap wstępnego przetwarzania (data preprocessing).

In [2]:
# Definicja DataFrame
df_student = pd.DataFrame({
    'imie': ['Anna', 'Piotr', 'Maria', 'Jan', 'Katarzyna', 'Tomasz', 'Magdalena', 'Paweł', 'Ewa', 'Michał'],
    'wiek': [20, 22, 21, np.nan, 23, 20, 22, np.nan, 21, 23],
    'ocena_matematyka': [4.5, np.nan, 5.0, 4.0, 3.5, 4.5, 5.0, 3.5, np.nan, 4.0],
    'ocena_fizyka': [5.0, 4.5, np.nan, 4.0, 4.5, np.nan, 5.0, 4.0, 4.5, np.nan],
    'ocena_informatyka': [4.0, 3.5, 4.5, np.nan, 5.0, 3.5, 4.5, 4.0, np.nan, 4.5],
    'miasto': ['Warszawa', 'Kraków', 'Wrocław', 'Poznań', 'Gdańsk', np.nan, 'Warszawa', 'Kraków', 'Wrocław', 'Poznań']
})

In [3]:
# 1. Sprawdzenie czy są brakujące wartości
print("1. Sprawdzenie brakujących wartości (True = brak):")
print(df_student.isnull())
# lub: df.isna()
print("\n" + "="*60 + "\n")

1. Sprawdzenie brakujących wartości (True = brak):
    imie   wiek  ocena_matematyka  ocena_fizyka  ocena_informatyka  miasto
0  False  False             False         False              False   False
1  False  False              True         False              False   False
2  False  False             False          True              False   False
3  False   True             False         False               True   False
4  False  False             False         False              False   False
5  False  False             False          True              False    True
6  False  False             False         False              False   False
7  False   True             False         False              False   False
8  False  False              True         False               True   False
9  False  False             False          True              False   False

============================================================

In [4]:
# 2. Liczba brakujących wartości w każdej kolumnie
print("2. Liczba brakujących wartości w każdej kolumnie:")
print(df_student.isna().sum())
print("\n" + "="*60 + "\n")

2. Liczba brakujących wartości w każdej kolumnie:
imie                 0
wiek                 2
ocena_matematyka     2
ocena_fizyka         3
ocena_informatyka    2
miasto               1
dtype: int64

============================================================

In [5]:
# 3. Procent brakujących wartości
print("3. Procent brakujących wartości w każdej kolumnie:")
print((df_student.isnull().sum() / len(df_student)) * 100)
print("\n" + "="*60 + "\n")

3. Procent brakujących wartości w każdej kolumnie:
imie                  0.0
wiek                 20.0
ocena_matematyka     20.0
ocena_fizyka         30.0
ocena_informatyka    20.0
miasto               10.0
dtype: float64

============================================================

In [6]:
# 4. Całkowita liczba brakujących wartości
print("4. Całkowita liczba brakujących wartości w całym DataFrame:")
print(df_student.isnull().sum().sum())

4. Całkowita liczba brakujących wartości w całym DataFrame:
10

## **Rozwiązanie kwestii brakujących danych**

* **Usuwanie rekordów** zawierających brakujące wartości.
* **Ręczne uzupełnianie** brakujących wartości.
* Uzupełnianie **brakujących wartości wskaźnikami** tendencji centralnej, np.: średnią, medianą czy dominantą.
  * **Średniej** używamy w przypadku cech numerycznych,
  * **mediany** w cechach porządkowych,
  * **dominantę** (czyli najczęściej powtarzającą się wartość) umieszczamy w cechach kategorialnych.

Uzupełnianie **najbardziej prawdopodobną wartością** przy użyciu modeli uczenia maszynowego, takich jak regresja, drzewa decyzyjne czy algorytm KNN.

## **Czym jest NaN i dlaczego jest wyjątkowy?**

**NaN** (Not a Number) – specjalna wartość reprezentująca brakujące dane.

Dane mogą zawierać różne oznaczenia braków:
* Tekstowe: "NA", "N/A", "brak", "?", "-"

* Numeryczne: 0, -999, -1​

* Inne: puste stringi ""

In [7]:
df = pd.DataFrame({
    'A': [1, np.nan, 3],# ✓ NaN - brakująca wartość ​
    'B': [4, None, 6],  # ✓ None - też brakująca ​
    'C': [7, 0, 9],     # ✗ 0 - NIE jest brakująca! ​
    'D': ['x', '', 'z'] # ✗ '' - NIE jest brakująca! ​
})

In [8]:
df.isnull().sum()

A    1
B    1
C    0
D    0
dtype: int64

## **Usuwanie brakujących wartości**

Usuń wiersze z DOWOLNĄ brakującą wartością (domyślnie) ​

```
df.dropna()
df.dropna(how='any')
```

Usuń wiersze tylko gdy WSZYSTKIE wartości są brakujące df.dropna(how='all')
```
df.dropna(how="all")
```

Usuń kolumny z brakującymi wartościami
```
df.dropna(axis=1)
```

## **Uzupełnienie średnią lub modą​**

W pandas *dataFrame* możemy uzupełnić brakujące wartości za pomocą funkcji `fillna()`.
* Przyjmuje ona jedną wartość, która będzie wstawiana w pustych pozycjach lub zamiast wartości NaN.

Uzupełnia wszystkie brakujące wartości w kolumnie age średnią obliczoną z tejże kolumny

```data['age'] = data.age.fillna(data.age.mean())​```

Uzupełnia wszystkie brakujące wartości w kolumnie income medianą obliczoną z tejże kolumny

```data['income']=data.income.fillna(data.income.median())```

Zastępuje wszystkie brakujące wartości w kolumnie gender (kolumna kategorii) dominantą wyliczoną z tejże kolumny​

```data['gender']=data['gender'].fillna(data['gender'].mode()[0])​```

In [9]:
df_student["wiek"] = df_student.wiek.fillna(df_student.wiek.mean())
df_student

,imie,wiek,ocena_matematyka,ocena_fizyka,ocena_informatyka,miasto
0,Anna,20.0,4.5,5.0,4.0,Warszawa
1,Piotr,22.0,NaN,4.5,3.5,Kraków
2,Maria,21.0,5.0,NaN,4.5,Wrocław
3,Jan,21.5,4.0,4.0,NaN,Poznań
4,Katarzyna,23.0,3.5,4.5,5.0,Gdańsk
5,Tomasz,20.0,4.5,NaN,3.5,NaN
6,Magdalena,22.0,5.0,5.0,4.5,Warszawa
7,Paweł,21.5,3.5,4.0,4.0,Kraków
8,Ewa,21.0,NaN,4.5,NaN,Wrocław
9,Michał,23.0,4.0,NaN,4.5,Poznań

In [10]:
df_student["ocena_matematyka"] = df_student["ocena_matematyka"] .fillna(df_student["ocena_matematyka"] .mean())
df_student

,imie,wiek,ocena_matematyka,ocena_fizyka,ocena_informatyka,miasto
0,Anna,20.0,4.50,5.0,4.0,Warszawa
1,Piotr,22.0,4.25,4.5,3.5,Kraków
2,Maria,21.0,5.00,NaN,4.5,Wrocław
3,Jan,21.5,4.00,4.0,NaN,Poznań
4,Katarzyna,23.0,3.50,4.5,5.0,Gdańsk
5,Tomasz,20.0,4.50,NaN,3.5,NaN
6,Magdalena,22.0,5.00,5.0,4.5,Warszawa
7,Paweł,21.5,3.50,4.0,4.0,Kraków
8,Ewa,21.0,4.25,4.5,NaN,Wrocław
9,Michał,23.0,4.00,NaN,4.5,Poznań

In [11]:
df_student["miasto"] = df_student["miasto"].fillna(df_student["miasto"] .mode()[0])
df_student

,imie,wiek,ocena_matematyka,ocena_fizyka,ocena_informatyka,miasto
0,Anna,20.0,4.50,5.0,4.0,Warszawa
1,Piotr,22.0,4.25,4.5,3.5,Kraków
2,Maria,21.0,5.00,NaN,4.5,Wrocław
3,Jan,21.5,4.00,4.0,NaN,Poznań
4,Katarzyna,23.0,3.50,4.5,5.0,Gdańsk
5,Tomasz,20.0,4.50,NaN,3.5,Kraków
6,Magdalena,22.0,5.00,5.0,4.5,Warszawa
7,Paweł,21.5,3.50,4.0,4.0,Kraków
8,Ewa,21.0,4.25,4.5,NaN,Wrocław
9,Michał,23.0,4.00,NaN,4.5,Poznań

## **Obsługa brakujących danych jako stringi**

**Problem**
* Dane często zawierają braki zapisane jako tekst: **"NA", "N/A", "brak", "?", "-", "brak danych"**

* Pandas **nie rozpoznaje** ich automatycznie jako brakujące wartości!

### **Rozwiązanie 1: Wczytywanie z pliku CSV**

```
import pandas as pd

# Definiujemy listę wartości oznaczających brak
braki = ['NA', 'N/A', 'brak', 'brak danych', '?', '-', '']

# Wczytujemy plik z parametrem na_values
df = pd.read_csv('dane.csv', na_values=braki)

```

### **Rozwiązanie 2: Zamiana po wczytaniu**

```
# Zamieniamy wybrane stringi na NaN
df.replace(['NA', 'N/A', 'brak', 'brak danych', '?', '-'], np.nan, inplace=True)

# LUB dla konkretnej kolumny
df['kolumna'] = df['kolumna'].replace('brak', np.nan)
```

# **Zadanie**:

**Dane**: Plik *nieruchomosci.csv* - 45 ofert sprzedaży mieszkań

**Polecenie**

* Wczytaj dane i przeanalizuj problem brakujących wartości

* Zdecyduj, jak poradzić sobie z brakami w poszczególnych kolumnach

* Uzasadnij swoje wybory i zaimplementuj rozwiązanie

**Do przemyślenia**

* Jakie typy zmiennych masz w danych?
* Czy wszystkie braki powinny być obsłużone tak samo?
* Jakie konsekwencje niesie każda metoda?
* Jak to wpływa na eksploracyjną analizę danych?

---
# ✅ Rozwiązanie zadania

## 1. Wczytanie danych i analiza braków

W pliku braki są zapisane na **wiele sposobów**, zależnie od kolumny:

| Rodzaj | Przykłady w danych |
|--------|--------------------|
| tekstowe znaczniki | `NA`, `N/A`, `brak`, `?` |
| sentinele liczbowe | `-999` (piętro, cena_m2), `-1` (cena_m2) |
| wartości nielogiczne | `powierzchnia = 0` (mieszkanie nie ma 0 m²) |
| błąd wpisu / obcy język | `stan = 很好` (chiń. „bardzo dobrze") |

Dlatego samo `read_csv` z domyślnym `na_values` **nie wychwyci wszystkiego** — trzeba
obsłużyć braki kolumna po kolumnie, bo mają różne znaczenie.

In [12]:
# Wczytujemy plik, od razu zamieniając tekstowe znaczniki braku na NaN
braki_tekstowe = ['NA', 'N/A', 'brak', 'brak danych', '?', '-', '']
df = pd.read_csv('nieruchomosci.csv', na_values=braki_tekstowe)

print("Kształt danych:", df.shape)
print("\nTypy kolumn:")
print(df.dtypes)
df.head()

Kształt danych: (45, 13)

Typy kolumn:
id                 int64
miasto               str
dzielnica            str
powierzchnia     float64
liczba_pokoi       int64
rok_budowy       float64
pietro           float64
liczba_pieter      int64
parking              str
balkon               str
stan                 str
cena_m2            int64
cena_total         int64
dtype: object

,id,miasto,dzielnica,powierzchnia,liczba_pokoi,rok_budowy,pietro,liczba_pieter,parking,balkon,stan,cena_m2,cena_total
0,1,Warszawa,Mokotów,65.0,3,2015.0,4.0,10,Tak,Tak,Dobry,12500,812500
1,2,Kraków,Krowodrza,48.0,2,NaN,2.0,5,Nie,Tak,很好,10200,489600
2,3,Wrocław,Krzyki,72.0,3,2010.0,NaN,4,Tak,Nie,Dobry,9800,705600
3,4,Poznań,Grunwald,55.0,2,2018.0,3.0,8,Tak,Tak,Bardzo dobry,11000,605000
4,5,Gdańsk,Wrzeszcz,80.0,4,1998.0,1.0,3,NaN,Tak,Do remontu,8500,680000

In [13]:
# Braki wychwycone przez na_values (znaczniki tekstowe -> NaN):
print("Braki po wczytaniu (tylko znaczniki tekstowe):")
print(df.isna().sum())

# Ale w danych zostały jeszcze UKRYTE braki: sentinele liczbowe i wartości nielogiczne
print("\n--- ukryte braki / wartości podejrzane ---")
print("powierzchnia == 0 :", (df['powierzchnia'] == 0).sum(), "(mieszkanie nie ma 0 m²)")
print("pietro == -999    :", (df['pietro'] == -999).sum(), "(sentinel braku)")
print("cena_m2 <= 0      :", (df['cena_m2'] <= 0).sum(), "(-1 oraz -999)")
print("\nUnikalne wartości 'stan':", list(df['stan'].dropna().unique()))
print("  -> '很好' to błąd wpisu (chiń. 'bardzo dobrze'), a nie osobna kategoria")

Braki po wczytaniu (tylko znaczniki tekstowe):
id               0
miasto           0
dzielnica        0
powierzchnia     6
liczba_pokoi     0
rok_budowy       7
pietro           1
liczba_pieter    0
parking          5
balkon           3
stan             0
cena_m2          0
cena_total       0
dtype: int64

--- ukryte braki / wartości podejrzane ---
powierzchnia == 0 : 3 (mieszkanie nie ma 0 m²)
pietro == -999    : 2 (sentinel braku)
cena_m2 <= 0      : 2 (-1 oraz -999)

Unikalne wartości 'stan': ['Dobry', '很好', 'Bardzo dobry', 'Do remontu']
  -> '很好' to błąd wpisu (chiń. 'bardzo dobrze'), a nie osobna kategoria

## 2. Typy zmiennych i strategia dla każdej kolumny

**Typy zmiennych:**
- **numeryczne ciągłe:** `powierzchnia`, `cena_m2`, `cena_total`
- **numeryczne dyskretne:** `liczba_pokoi`, `rok_budowy`, `pietro`, `liczba_pieter`
- **kategorialne:** `miasto`, `dzielnica`, `stan`, `parking` (Tak/Nie), `balkon` (Tak/Nie)

**Nie** — braki nie powinny być obsłużone tak samo. Strategia zależy od typu i znaczenia kolumny:

| Kolumna | Problem | Rozwiązanie | Uzasadnienie |
|---------|---------|-------------|--------------|
| `stan` | `很好` = błąd wpisu | zamiana na `Bardzo dobry` | to nie brak, tylko literówka/obcy język |
| `powierzchnia` | `0`, `NA`, `brak` | **przelicz** z `cena_total / cena_m2`, reszta → mediana | zależność biznesowa: cena_total ≈ powierzchnia × cena_m2 |
| `cena_m2` | `-1`, `-999` | **przelicz** z `cena_total / powierzchnia` | jw. — dokładniejsze niż średnia |
| `rok_budowy` | `NA`, `brak` | mediana (int) | rok musi być liczbą całkowitą, rozkład skośny → mediana |
| `pietro` | `-999`, `brak` | mediana (int) | dyskretna; `0` (parter) jest POPRAWNE, zostaje |
| `parking`, `balkon` | `?` | dominanta | zmienne kategorialne binarne |

**Kluczowa obserwacja:** `powierzchnia × cena_m2 = cena_total` (sprawdź: 65 × 12500 = 812500 ✓).
Dzięki temu brakującą wartość można **odtworzyć dokładnie** z dwóch pozostałych, zamiast zgadywać średnią.

In [14]:
# 3. Zamiana sentineli i wartości nielogicznych na NaN + naprawa błędu wpisu
df['powierzchnia'] = df['powierzchnia'].replace(0, np.nan)      # 0 m² niemożliwe
df['pietro']       = df['pietro'].replace(-999, np.nan)         # -999 = brak
df['cena_m2']      = df['cena_m2'].replace([-1, -999], np.nan)  # ujemna cena niemożliwa
df['stan']         = df['stan'].replace('很好', 'Bardzo dobry') # błąd wpisu -> kategoria

print("Braki po ujawnieniu ukrytych sentineli:")
print(df.isna().sum())
print("\nProcent braków w kolumnie (%):")
print((df.isna().mean() * 100).round(1))

Braki po ujawnieniu ukrytych sentineli:
id               0
miasto           0
dzielnica        0
powierzchnia     9
liczba_pokoi     0
rok_budowy       7
pietro           3
liczba_pieter    0
parking          5
balkon           3
stan             0
cena_m2          2
cena_total       0
dtype: int64

Procent braków w kolumnie (%):
id                0.0
miasto            0.0
dzielnica         0.0
powierzchnia     20.0
liczba_pokoi      0.0
rok_budowy       15.6
pietro            6.7
liczba_pieter     0.0
parking          11.1
balkon            6.7
stan              0.0
cena_m2           4.4
cena_total        0.0
dtype: float64

In [15]:
# 4. Uzupełnianie zależne (najdokładniejsze): powierzchnia * cena_m2 = cena_total
# a) brak powierzchni, ale znamy cena_m2 i cena_total -> odtwórz powierzchnię
m = df['powierzchnia'].isna() & df['cena_m2'].notna() & df['cena_total'].notna()
df.loc[m, 'powierzchnia'] = (df.loc[m, 'cena_total'] / df.loc[m, 'cena_m2']).round()
print(f"Odtworzono powierzchnię z ceny dla {m.sum()} wierszy")

# b) brak cena_m2, ale znamy powierzchnię i cena_total -> odtwórz cena_m2
m = df['cena_m2'].isna() & df['powierzchnia'].notna() & df['cena_total'].notna()
df.loc[m, 'cena_m2'] = (df.loc[m, 'cena_total'] / df.loc[m, 'powierzchnia']).round()
print(f"Odtworzono cena_m2 z powierzchni dla {m.sum()} wierszy")

Odtworzono powierzchnię z ceny dla 9 wierszy
Odtworzono cena_m2 z powierzchni dla 2 wierszy

In [16]:
# 5. Uzupełnienie pozostałych braków wg typu zmiennej
# numeryczne dyskretne -> mediana, rzut na int (rok, piętro to liczby całkowite)
for col in ['rok_budowy', 'pietro']:
    df[col] = df[col].fillna(df[col].median()).astype(int)

# numeryczna ciągła, gdyby coś zostało -> mediana (odporna na skośność cen)
df['powierzchnia'] = df['powierzchnia'].fillna(df['powierzchnia'].median())
df['cena_m2']      = df['cena_m2'].fillna(df['cena_m2'].median())

# kategorialne binarne -> dominanta (najczęstsza wartość)
for col in ['parking', 'balkon']:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Braki po pełnym uzupełnieniu:")
print(df.isna().sum())
print("\nŁączna liczba braków:", int(df.isna().sum().sum()))

Braki po pełnym uzupełnieniu:
id               0
miasto           0
dzielnica        0
powierzchnia     0
liczba_pokoi     0
rok_budowy       0
pietro           0
liczba_pieter    0
parking          0
balkon           0
stan             0
cena_m2          0
cena_total       0
dtype: int64

Łączna liczba braków: 0

In [17]:
# 6. Konsekwencje metod: porównanie z prostym usunięciem wierszy (dropna)
df_raw = pd.read_csv('nieruchomosci.csv', na_values=braki_tekstowe)
print("Gdybyśmy użyli dropna() na surowych danych:")
print(f"  wierszy przed: {len(df_raw)}  ->  po dropna: {len(df_raw.dropna())}")
print(f"  STRATA: {len(df_raw) - len(df_raw.dropna())} wierszy "
      f"({(1 - len(df_raw.dropna())/len(df_raw))*100:.0f}% danych!)")

print("\nWpływ na EDA — średnia powierzchnia:")
print(f"  usunięcie (dropna):  {df_raw['powierzchnia'].dropna().mean():.1f} m² "
      f"(ale 0 i sentinele zawyżają/zaniżają!)")
print(f"  po imputacji:        {df['powierzchnia'].mean():.1f} m²")
print("\nDataFrame gotowy do analizy — typy kolumn:")
print(df.dtypes)

Gdybyśmy użyli dropna() na surowych danych:
  wierszy przed: 45  ->  po dropna: 26
  STRATA: 19 wierszy (42% danych!)

Wpływ na EDA — średnia powierzchnia:
  usunięcie (dropna):  59.7 m² (ale 0 i sentinele zawyżają/zaniżają!)
  po imputacji:        64.9 m²

DataFrame gotowy do analizy — typy kolumn:
id                 int64
miasto               str
dzielnica            str
powierzchnia     float64
liczba_pokoi       int64
rok_budowy         int64
pietro             int64
liczba_pieter      int64
parking              str
balkon               str
stan                 str
cena_m2          float64
cena_total         int64
dtype: object

## 3. Wnioski — konsekwencje metod i wpływ na EDA

- **Usuwanie wierszy (`dropna`)** — najprostsze, ale przy tak rozproszonych brakach traci ~połowę
  danych. Nie do przyjęcia przy 44 rekordach. Dodatkowo *nie usuwa* ukrytych braków (0, -999),
  które i tak zepsułyby statystyki.
- **Imputacja wskaźnikiem centralnym** (średnia/mediana/dominanta) — zachowuje wszystkie wiersze,
  ale **zmniejsza wariancję** i może zaburzyć korelacje. Dla cen (rozkład skośny) mediana jest
  bezpieczniejsza niż średnia.
- **Imputacja zależna** (`cena_total / cena_m2`) — tu najlepsza: odtwarza wartość *dokładnie*
  z zależności biznesowej, nie wprowadzając sztucznego „spłaszczenia" rozkładu.
- **Wpływ na EDA:** kluczowe było wykrycie braków *ukrytych* (`0`, `-999`, `-1`, `很好`). Gdybyśmy
  je zostawili, średnia powierzchni, ceny i histogramy byłyby całkowicie zniekształcone
  (np. `-999` w cenie zaniża średnią o tysiące). Świadoma obsługa braków = wiarygodna analiza.